### ISSUE TITLE
Issuses with displaying the site with Safari 9

### ISSUE THREAD

**Issue by hblasins** [reefsource/reefsource#38]
David Brainard said that the site didn't work on his machine under Safari 9.

**Comment by lukasz-karolewski** [comment]
official apple support for safari 9 ended in 2016 with Mavericks (it is current  - 4 version of macOS)
while it would be probably possible to make it compatible there is unknown, potentially large effort associated with that

**Comment by hblasins** [comment]
Sounds good!
